# Display a box
print(" ###########")
print(" #   Y  Y  #")
print(" #         #")
print(" ###########")
print("################")
print("#              #")
print("#              ######")
print("#              #")
print("################")
print("    ##      ##")
print("    ##      ##")